"""Fleet catalog: a generated, read-only projection over separate wiki roots.

The catalog aggregates the authoritative per-wiki cards (registry entries of
schema v1/v2 vaults and standalone ``wiki-card.json`` roots) without moving or
combining any content. It is always a projection: cards stay authoritative,
output is deterministic and byte-stable for the same inputs, and the optional
human-readable projection can be drift-checked against the cards so the two
never silently diverge.

Cards may redact sensitive fields, or even their existence, from the
projection. Broken, unreachable, and stale entries are stated explicitly;
nothing is ever silently omitted. Page content is never read into the catalog.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

from .access import effective_policy, policy_findings
from .capture import list_proposals
from .card import CardError, card_file, load_wiki_card
from .fsops import content_hash, resolve_contained
from .models import parse_document
from .registry import RegistryError, WikiEntry, load_registry, registry_file

CATALOG_HEADER = "<!-- generated by megamind: do not edit by hand -->"


@dataclass
class RootRef:
    """One wiki root taking part in the catalog, with its display label."""

    label: str
    path: Path


@dataclass
class Catalog:
    rows: list[dict[str, object]] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    @property
    def catalog_hash(self) -> str:
        canonical = json.dumps(self.rows, sort_keys=True)
        return content_hash(canonical)


def discover_roots(estate: Path) -> list[RootRef]:
    """Find wiki roots: the estate directory itself plus its direct children.

    A directory qualifies when it carries a Megamind registry or a canonical
    wiki card. Discovery never recurses below one level, so nested wiki content
    is never mistaken for a root. Labels keep the estate prefix as passed, so
    follow-up commands built from them run unchanged from the same directory.
    """
    refs: list[RootRef] = []
    if registry_file(estate).is_file() or card_file(estate).is_file():
        refs.append(RootRef(label=str(estate), path=estate))
    if estate.is_dir():
        for child in sorted(estate.iterdir()):
            if not child.is_dir() or child.name.startswith("."):
                continue
            if registry_file(child).is_file() or card_file(child).is_file():
                refs.append(RootRef(label=str(estate / child.name), path=child))
    return refs


def _count_pages(root: Path, rel: str) -> int | None:
    try:
        directory = resolve_contained(root, rel)
    except ValueError:
        return None
    if not directory.is_dir():
        return None
    return sum(1 for path in directory.rglob("*.md") if path.is_file())


def _open_proposals(root: Path) -> int:
    open_count = 0
    for proposal_file in list_proposals(root):
        try:
            document = parse_document(proposal_file.read_text(encoding="utf-8"))
        except (ValueError, OSError, UnicodeDecodeError):
            continue
        if str(document.frontmatter.get("status", "")) == "proposed":
            open_count += 1
    return open_count


def _staleness(entry: WikiEntry, today: date | None) -> bool | None:
    """Read-time staleness from the declared freshness fields; never stored."""
    if today is None or not entry.freshness.last_confirmed:
        return None
    if entry.freshness.half_life_days is None:
        return None
    try:
        confirmed = date.fromisoformat(entry.freshness.last_confirmed)
    except ValueError:
        return None
    return (today - confirmed).days > entry.freshness.half_life_days


def _root_health(root: Path) -> dict[str, object]:
    """Card-safe maintenance facts that never inspect compiled page content."""
    return {
        "open_proposals": _open_proposals(root),
        "doctor": "not-applicable",
        "stale_pages": None,
    }


def _maintenance(
    entry: WikiEntry, source: str, root: Path, health: dict[str, object]
) -> dict[str, object]:
    pages = _count_pages(root, "wiki" if source == "wiki-card" else entry.path)
    return {
        "pages": pages,
        "open_proposals": health["open_proposals"],
        "doctor": health["doctor"],
        "stale_pages": health["stale_pages"],
    }


def _plain_list(value: object) -> list[str]:
    if isinstance(value, list):
        return [str(item) for item in value]
    return []


def _row_from_entry(
    ref: RootRef,
    entry: WikiEntry,
    source: str,
    registry_version: int | None,
    today: date | None,
    health: dict[str, object],
) -> dict[str, object]:
    policy = effective_policy(entry)
    row: dict[str, object] = {
        "name": entry.name,
        "root": ref.label,
        "status": "ok",
        "source": source,
        "registry_version": registry_version,
        "purpose": entry.purpose or entry.description,
        "answers": entry.answers,
        "does_not_answer": entry.does_not_answer,
        "scope_boundaries": entry.scope_boundaries,
        "owners": entry.owners,
        "sensitivity": policy.sensitivity,
        "privacy": entry.privacy or None,
        "model_access": {
            "local": policy.local,
            "cloud": policy.cloud,
            "derived": [axis for axis in policy.derived if axis in ("local", "cloud")],
        },
        "routing_mode": policy.routing_mode,
        "catalog_visibility": policy.catalog_visibility,
        # Governance, not access: a provisional wiki is projected in full but
        # is never trusted active knowledge until an evaluation pass clears it.
        "provisional": entry.provisional,
        "source_policy": {
            "summary": entry.source_policy.summary,
            "allowlist": entry.source_policy.allowlist,
            "allowlist_status": entry.source_policy.allowlist_status,
        },
        "freshness": {
            "half_life_days": entry.freshness.half_life_days,
            "last_confirmed": entry.freshness.last_confirmed or None,
            "stale": _staleness(entry, today),
        },
        "examples": entry.examples,
        "triggers": entry.triggers,
        "negative_triggers": entry.negative_triggers,
        "keywords": entry.keywords,
        "dependencies": entry.dependencies,
        "paths": {"card": entry.card, "digest": entry.digest, "index": entry.index},
        "context_budget": {
            "max_candidates": entry.context_budget.max_candidates,
            "max_context_chars": entry.context_budget.max_context_chars,
        },
        "maintenance": _maintenance(entry, source, ref.path, health),
        "policy_issues": [finding.message for finding in policy_findings(entry)],
    }
    if row["freshness"]["stale"]:  # type: ignore[index]
        row["stale"] = True
    return row


_REDACTED_KEPT = ("name", "root", "status", "sensitivity", "purpose", "catalog_visibility")


def redact_row(row: dict[str, object]) -> dict[str, object]:
    """Apply the card's catalog visibility to its row."""
    visibility = str(row.get("catalog_visibility", "full"))
    if visibility == "full":
        return row
    if visibility == "hidden":
        return {
            "status": "redacted",
            "catalog_visibility": "hidden",
            "note": "a wiki is withheld from this projection by its card policy",
        }
    kept = {key: row[key] for key in _REDACTED_KEPT if key in row}
    kept["redacted"] = True
    kept["redacted_fields"] = sorted(set(row) - set(_REDACTED_KEPT))
    return kept


def _sort_key(row: dict[str, object]) -> tuple[int, str]:
    """Order rows by root/name, but sort withheld wikis last and unranked.

    A hidden wiki's position in the projection must not leak where its name
    sorts, so hidden rows go after every visible row and are ordered among
    themselves by a content hash of their identity instead of by that identity.
    """
    identity = f"{row.get('root')}/{row.get('name')}"
    if str(row.get("catalog_visibility", "")) == "hidden":
        return (1, content_hash(identity))
    return (0, identity)


def build_catalog(refs: list[RootRef], today: date | None = None) -> Catalog:
    """Aggregate every eligible root into internal (unredacted) rows."""
    catalog = Catalog()
    if not refs:
        catalog.notes.append("no wiki roots found")
    for ref in refs:
        if not ref.path.is_dir():
            catalog.rows.append(
                {
                    "name": ref.label,
                    "root": ref.label,
                    "status": "unreachable",
                    "error": "directory does not exist",
                }
            )
            continue
        if registry_file(ref.path).is_file():
            try:
                registry = load_registry(ref.path)
            except RegistryError as error:
                catalog.rows.append(
                    {
                        "name": ref.label,
                        "root": ref.label,
                        "status": "broken",
                        "error": str(error),
                    }
                )
                continue
            health = _root_health(ref.path)
            for entry in registry.wikis:
                catalog.rows.append(
                    _row_from_entry(ref, entry, "registry", registry.version, today, health)
                )
        elif card_file(ref.path).is_file():
            try:
                entry = load_wiki_card(ref.path)
            except (CardError, ValueError) as error:
                catalog.rows.append(
                    {
                        "name": ref.label,
                        "root": ref.label,
                        "status": "broken",
                        "error": str(error),
                    }
                )
                continue
            health = _root_health(ref.path)
            catalog.rows.append(_row_from_entry(ref, entry, "wiki-card", None, today, health))
        else:
            catalog.notes.append(
                f"{ref.label} carries no Megamind registry and no wiki card: "
                "nothing to project for this root"
            )
    catalog.rows.sort(key=_sort_key)
    return catalog


def visible_rows(catalog: Catalog) -> list[dict[str, object]]:
    """The projection boundary: redaction is applied here and only here."""
    return [redact_row(row) for row in catalog.rows]


def render_projection(catalog: Catalog) -> str:
    """Render the byte-stable human-readable projection from the same rows."""
    rows = visible_rows(catalog)
    lines = [
        CATALOG_HEADER,
        "# Wiki catalog",
        "",
        f"Generated projection of {len(rows)} entrie(s); the per-wiki cards are authoritative.",
        "Regenerate with `megamind-axi catalog --estate <dir> --emit-projection`.",
        "",
    ]
    for row in rows:
        status = str(row.get("status", "ok"))
        if status == "redacted":
            lines.append("## (withheld wiki)")
            lines.append("")
            lines.append(f"- {row.get('note', 'withheld by card policy')}")
            lines.append("")
            continue
        if status != "ok":
            lines.append(f"## {row.get('name')} ({row.get('root')})")
            lines.append("")
            lines.append(f"- status: {status}")
            lines.append(f"- error: {row.get('error', '')}")
            lines.append("")
            continue
        lines.append(f"## {row.get('name')} ({row.get('root')})")
        lines.append("")
        if row.get("redacted"):
            lines.append("- purpose: " + str(row.get("purpose") or "(unset)"))
            lines.append("- sensitivity: " + str(row.get("sensitivity")))
            lines.append("- redacted: " + ", ".join(_plain_list(row.get("redacted_fields"))))
            lines.append("")
            continue
        access = row["model_access"]
        assert isinstance(access, dict)
        lines.append("- purpose: " + str(row.get("purpose") or "(unset)"))
        lines.append(f"- sensitivity: {row.get('sensitivity')}")
        lines.append(f"- model access: local {access['local']}, cloud {access['cloud']}")
        lines.append(f"- routing mode: {row.get('routing_mode')}")
        if row.get("provisional"):
            lines.append("- provisional: yes (not trusted active knowledge yet)")
        policy = row["source_policy"]
        assert isinstance(policy, dict)
        if policy.get("summary") or policy.get("allowlist"):
            lines.append(
                f"- source policy: {policy.get('summary') or '(unset)'} "
                f"(allowlist: {policy.get('allowlist') or 'none'}, "
                f"{policy.get('allowlist_status')})"
            )
        if row.get("does_not_answer"):
            lines.append("- does not answer: " + "; ".join(_plain_list(row.get("does_not_answer"))))
        if row.get("triggers"):
            lines.append("- triggers: " + ", ".join(_plain_list(row.get("triggers"))))
        if row.get("owners"):
            lines.append("- owners: " + ", ".join(_plain_list(row.get("owners"))))
        if row.get("dependencies"):
            lines.append("- dependencies: " + ", ".join(_plain_list(row.get("dependencies"))))
        if row.get("stale"):
            lines.append("- stale: yes")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def check_projection(catalog: Catalog, projection_path: Path) -> str:
    """Drift validation: compare a checked-in projection against the cards."""
    if not projection_path.is_file():
        return "missing"
    actual = projection_path.read_text(encoding="utf-8")
    return "current" if actual == render_projection(catalog) else "drifted"
