"""Registry: the single source of truth for which wikis Megamind knows about.

The registry lives at ``<root>/.megamind/registry.json``. Paths inside it are
always relative to the root; absolute paths are rejected so a registry never
leaks machine-specific locations and stays portable between checkouts.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path

from .fsops import MEGAMIND_DIR, atomic_write, resolve_contained
from .models import PRIVACY_CLASSES

REGISTRY_PATH = Path(MEGAMIND_DIR) / "registry.json"
ROUTER_FILENAME = "ROUTER.md"
ROUTER_HEADER = "<!-- generated by megamind: do not edit by hand -->"
SUPPORTED_VERSIONS = (1,)


class RegistryError(ValueError):
    """The registry is missing, unreadable, or violates the schema."""

    code = "registry_invalid"


class RegistryNotInitialized(RegistryError):
    """No registry exists at this root yet."""

    code = "not_initialized"


@dataclass
class Budgets:
    """Context and lifecycle budgets. All values are deliberately small by default."""

    max_candidates: int = 5
    max_context_chars: int = 8000
    stale_days: int = 180
    micro_wiki_pages: int = 4
    top_level_topics: int = 3


@dataclass
class WikiEntry:
    """One registered wiki. All paths are root-relative POSIX strings."""

    name: str
    path: str
    privacy: str = "public-reference"
    description: str = ""
    keywords: list[str] = field(default_factory=list)
    card: str = ""
    digest: str = ""
    index: str = ""


@dataclass
class Registry:
    version: int = 1
    budgets: Budgets = field(default_factory=Budgets)
    wikis: list[WikiEntry] = field(default_factory=list)

    def wiki_by_name(self, name: str) -> WikiEntry | None:
        for wiki in self.wikis:
            if wiki.name == name:
                return wiki
        return None


_BUDGET_FIELDS = (
    "max_candidates",
    "max_context_chars",
    "stale_days",
    "micro_wiki_pages",
    "top_level_topics",
)
_WIKI_FIELDS = ("name", "path", "privacy", "description", "keywords", "card", "digest", "index")


def _type_name(value: object) -> str:
    return type(value).__name__


def _require_int(label: str, value: object) -> int:
    """Accept only genuine integers; JSON booleans are ints in Python but not budgets."""
    if isinstance(value, bool) or not isinstance(value, int):
        raise RegistryError(f"{label} must be an integer, got {_type_name(value)}")
    return value


def _require_str(label: str, value: object) -> str:
    if not isinstance(value, str):
        raise RegistryError(f"{label} must be a string, got {_type_name(value)}")
    return value


def _require_str_list(label: str, value: object) -> list[str]:
    if not isinstance(value, list):
        raise RegistryError(f"{label} must be a list of strings, got {_type_name(value)}")
    return [_require_str(f"{label}[{index}]", item) for index, item in enumerate(value)]


def _require_mapping(label: str, value: object) -> dict[str, object]:
    if not isinstance(value, dict):
        raise RegistryError(f"{label} must be a JSON object, got {_type_name(value)}")
    return {_require_str(f"{label} key", key): item for key, item in value.items()}


def _reject_unknown(label: str, data: dict[str, object], allowed: tuple[str, ...]) -> None:
    unknown = sorted(set(data) - set(allowed))
    if unknown:
        raise RegistryError(f"{label} has unknown field(s): {', '.join(unknown)}")


def _budgets_from_json(value: object) -> Budgets:
    data = _require_mapping("budgets", value)
    _reject_unknown("budgets", data, _BUDGET_FIELDS)
    defaults = Budgets()
    values = {
        name: _require_int(f"budget {name}", data[name])
        if name in data
        else getattr(defaults, name)
        for name in _BUDGET_FIELDS
    }
    return Budgets(
        max_candidates=values["max_candidates"],
        max_context_chars=values["max_context_chars"],
        stale_days=values["stale_days"],
        micro_wiki_pages=values["micro_wiki_pages"],
        top_level_topics=values["top_level_topics"],
    )


def _wiki_from_json(position: int, value: object) -> WikiEntry:
    label = f"wikis[{position}]"
    data = _require_mapping(label, value)
    _reject_unknown(label, data, _WIKI_FIELDS)
    defaults = WikiEntry(name="", path="")
    return WikiEntry(
        name=_require_str(f"{label} name", data.get("name", defaults.name)),
        path=_require_str(f"{label} path", data.get("path", defaults.path)),
        privacy=_require_str(f"{label} privacy", data.get("privacy", defaults.privacy)),
        description=_require_str(f"{label} description", data.get("description", "")),
        keywords=_require_str_list(f"{label} keywords", data.get("keywords", [])),
        card=_require_str(f"{label} card", data.get("card", "")),
        digest=_require_str(f"{label} digest", data.get("digest", "")),
        index=_require_str(f"{label} index", data.get("index", "")),
    )


def _require_relative(label: str, value: str) -> None:
    if value.startswith("/") or value.startswith("~") or ":" in value.split("/")[0]:
        raise RegistryError(f"{label} must be a root-relative path, got: {value}")
    if ".." in Path(value).parts:
        raise RegistryError(f"{label} must not contain '..': {value}")


def validate_registry(registry: Registry) -> None:
    """Enforce the registry schema. Every violation is a RegistryError, never a crash."""
    _require_int("version", registry.version)
    if registry.version not in SUPPORTED_VERSIONS:
        raise RegistryError(f"unsupported registry version: {registry.version}")
    budgets = registry.budgets
    for name in _BUDGET_FIELDS:
        budget = _require_int(f"budget {name}", getattr(budgets, name))
        if name in ("max_candidates", "max_context_chars", "stale_days") and budget <= 0:
            raise RegistryError(f"budget {name} must be positive")
    if not isinstance(registry.wikis, list):
        raise RegistryError(f"wikis must be a list, got {_type_name(registry.wikis)}")
    seen: set[str] = set()
    for position, wiki in enumerate(registry.wikis):
        if not isinstance(wiki, WikiEntry):
            raise RegistryError(f"wikis[{position}] must be a wiki entry, got {_type_name(wiki)}")
        name = _require_str(f"wikis[{position}] name", wiki.name)
        if not name:
            raise RegistryError("wiki entry without a name")
        if name in seen:
            raise RegistryError(f"duplicate wiki name: {name}")
        seen.add(name)
        _require_str_list(f"wiki {name} keywords", wiki.keywords)
        if not _require_str(f"wiki {name} path", wiki.path):
            raise RegistryError(f"wiki {name} has no path")
        for label, value in (
            (f"wiki {name} path", wiki.path),
            (f"wiki {name} card", _require_str(f"wiki {name} card", wiki.card)),
            (f"wiki {name} digest", _require_str(f"wiki {name} digest", wiki.digest)),
            (f"wiki {name} index", _require_str(f"wiki {name} index", wiki.index)),
        ):
            if value:
                _require_relative(label, value)
        if wiki.privacy not in PRIVACY_CLASSES:
            raise RegistryError(
                f"wiki {wiki.name} has invalid privacy class: {wiki.privacy} "
                f"(expected one of {', '.join(PRIVACY_CLASSES)})"
            )


def registry_file(root: Path) -> Path:
    return resolve_contained(root, REGISTRY_PATH)


def load_registry(root: Path) -> Registry:
    path = registry_file(root)
    if not path.is_file():
        raise RegistryNotInitialized(
            f"no registry at {REGISTRY_PATH.as_posix()}; run 'megamind-axi init .' first"
        )
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise RegistryError(f"registry is not valid JSON: {error}") from error
    data = _require_mapping("registry root", raw)
    _reject_unknown("registry", data, ("version", "budgets", "wikis"))
    raw_wikis = data.get("wikis", [])
    if not isinstance(raw_wikis, list):
        raise RegistryError(f"wikis must be a list, got {_type_name(raw_wikis)}")
    registry = Registry(
        version=_require_int("version", data.get("version", 0)),
        budgets=_budgets_from_json(data.get("budgets", {})),
        wikis=[_wiki_from_json(position, entry) for position, entry in enumerate(raw_wikis)],
    )
    validate_registry(registry)
    return registry


def save_registry(root: Path, registry: Registry) -> Path:
    validate_registry(registry)
    payload = json.dumps(asdict(registry), indent=2, sort_keys=True) + "\n"
    return atomic_write(root, REGISTRY_PATH, payload)


def generate_router(registry: Registry) -> str:
    """Render the generated top-level router page from the registry.

    The router is a human/agent readable projection of the registry. It is
    regenerated, never hand-edited; doctor verifies it matches the registry.
    """
    lines = [
        ROUTER_HEADER,
        "# Router",
        "",
        "Start here. Open the smallest artifact that can answer the question:",
        "routing card, then digest, then index, then exact pages.",
        "",
    ]
    for wiki in sorted(registry.wikis, key=lambda w: w.name):
        lines.append(f"## {wiki.name}")
        lines.append("")
        if wiki.description:
            lines.append(wiki.description)
            lines.append("")
        lines.append(f"- path: `{wiki.path}`")
        lines.append(f"- privacy: `{wiki.privacy}`")
        if wiki.card:
            lines.append(f"- card: `{wiki.card}`")
        if wiki.digest:
            lines.append(f"- digest: `{wiki.digest}`")
        if wiki.index:
            lines.append(f"- index: `{wiki.index}`")
        if wiki.keywords:
            lines.append(f"- keywords: {', '.join(wiki.keywords)}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"
