"""Registry: the single source of truth for which wikis Megamind knows about.

The registry lives at ``<root>/.megamind/registry.json``. Paths inside it are
always relative to the root; absolute paths are rejected so a registry never
leaks machine-specific locations and stays portable between checkouts.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path

from .fsops import MEGAMIND_DIR, atomic_write, resolve_contained
from .models import PRIVACY_CLASSES

REGISTRY_PATH = Path(MEGAMIND_DIR) / "registry.json"
ROUTER_FILENAME = "ROUTER.md"
ROUTER_HEADER = "<!-- generated by megamind: do not edit by hand -->"
SUPPORTED_VERSIONS = (1,)


class RegistryError(ValueError):
    """The registry is missing, unreadable, or violates the schema."""

    code = "registry_invalid"


class RegistryNotInitialized(RegistryError):
    """No registry exists at this root yet."""

    code = "not_initialized"


@dataclass
class Budgets:
    """Context and lifecycle budgets. All values are deliberately small by default."""

    max_candidates: int = 5
    max_context_chars: int = 8000
    stale_days: int = 180
    micro_wiki_pages: int = 4
    top_level_topics: int = 3


@dataclass
class WikiEntry:
    """One registered wiki. All paths are root-relative POSIX strings."""

    name: str
    path: str
    privacy: str = "public-reference"
    description: str = ""
    keywords: list[str] = field(default_factory=list)
    card: str = ""
    digest: str = ""
    index: str = ""


@dataclass
class Registry:
    version: int = 1
    budgets: Budgets = field(default_factory=Budgets)
    wikis: list[WikiEntry] = field(default_factory=list)

    def wiki_by_name(self, name: str) -> WikiEntry | None:
        for wiki in self.wikis:
            if wiki.name == name:
                return wiki
        return None


def _require_relative(label: str, value: str) -> None:
    if value.startswith("/") or value.startswith("~") or ":" in value.split("/")[0]:
        raise RegistryError(f"{label} must be a root-relative path, got: {value}")
    if ".." in Path(value).parts:
        raise RegistryError(f"{label} must not contain '..': {value}")


def validate_registry(registry: Registry) -> None:
    if registry.version not in SUPPORTED_VERSIONS:
        raise RegistryError(f"unsupported registry version: {registry.version}")
    budgets = registry.budgets
    for name in ("max_candidates", "max_context_chars", "stale_days"):
        if getattr(budgets, name) <= 0:
            raise RegistryError(f"budget {name} must be positive")
    seen: set[str] = set()
    for wiki in registry.wikis:
        if not wiki.name:
            raise RegistryError("wiki entry without a name")
        if wiki.name in seen:
            raise RegistryError(f"duplicate wiki name: {wiki.name}")
        seen.add(wiki.name)
        if not wiki.path:
            raise RegistryError(f"wiki {wiki.name} has no path")
        for label, value in (
            (f"wiki {wiki.name} path", wiki.path),
            (f"wiki {wiki.name} card", wiki.card),
            (f"wiki {wiki.name} digest", wiki.digest),
            (f"wiki {wiki.name} index", wiki.index),
        ):
            if value:
                _require_relative(label, value)
        if wiki.privacy not in PRIVACY_CLASSES:
            raise RegistryError(
                f"wiki {wiki.name} has invalid privacy class: {wiki.privacy} "
                f"(expected one of {', '.join(PRIVACY_CLASSES)})"
            )


def registry_file(root: Path) -> Path:
    return resolve_contained(root, REGISTRY_PATH)


def load_registry(root: Path) -> Registry:
    path = registry_file(root)
    if not path.is_file():
        raise RegistryNotInitialized(
            f"no registry at {REGISTRY_PATH.as_posix()}; run 'megamind-axi init .' first"
        )
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise RegistryError(f"registry is not valid JSON: {error}") from error
    if not isinstance(raw, dict):
        raise RegistryError("registry root must be a JSON object")
    try:
        budgets = Budgets(**raw.get("budgets", {}))
        wikis = [WikiEntry(**entry) for entry in raw.get("wikis", [])]
        registry = Registry(version=int(raw.get("version", 0)), budgets=budgets, wikis=wikis)
    except TypeError as error:
        raise RegistryError(f"registry schema mismatch: {error}") from error
    validate_registry(registry)
    return registry


def save_registry(root: Path, registry: Registry) -> Path:
    validate_registry(registry)
    payload = json.dumps(asdict(registry), indent=2, sort_keys=True) + "\n"
    return atomic_write(root, REGISTRY_PATH, payload)


def generate_router(registry: Registry) -> str:
    """Render the generated top-level router page from the registry.

    The router is a human/agent readable projection of the registry. It is
    regenerated, never hand-edited; doctor verifies it matches the registry.
    """
    lines = [
        ROUTER_HEADER,
        "# Router",
        "",
        "Start here. Open the smallest artifact that can answer the question:",
        "routing card, then digest, then index, then exact pages.",
        "",
    ]
    for wiki in sorted(registry.wikis, key=lambda w: w.name):
        lines.append(f"## {wiki.name}")
        lines.append("")
        if wiki.description:
            lines.append(wiki.description)
            lines.append("")
        lines.append(f"- path: `{wiki.path}`")
        lines.append(f"- privacy: `{wiki.privacy}`")
        if wiki.card:
            lines.append(f"- card: `{wiki.card}`")
        if wiki.digest:
            lines.append(f"- digest: `{wiki.digest}`")
        if wiki.index:
            lines.append(f"- index: `{wiki.index}`")
        if wiki.keywords:
            lines.append(f"- keywords: {', '.join(wiki.keywords)}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"
