"""Registry: the single source of truth for which wikis Megamind knows about.

The registry lives at ``<root>/.megamind/registry.json``. Paths inside it are
always relative to the root; absolute paths are rejected so a registry never
leaks machine-specific locations and stays portable between checkouts.

Schema version 2 is additive: every v1 registry loads unchanged, with the new
card fields (purpose, scope, owners, sensitivity, model access, source policy,
freshness, examples, triggers, dependencies, budgets, catalog visibility)
falling back to restrictive deterministic defaults. ``megamind-axi migrate``
upgrades a v1 file in place; doctor warns about v1 registries until then.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import date
from pathlib import Path

from .fsops import MEGAMIND_DIR, append_audit, atomic_write, backup_existing, resolve_contained
from .models import (
    ALLOWLIST_STATUSES,
    CATALOG_VISIBILITIES,
    MODEL_ACCESS_LEVELS,
    PRIVACY_CLASSES,
    PRIVACY_SENSITIVITY,
    ROUTING_MODES,
    SENSITIVITY_CLASSES,
)

REGISTRY_PATH = Path(MEGAMIND_DIR) / "registry.json"
ROUTER_FILENAME = "ROUTER.md"
ROUTER_HEADER = "<!-- generated by megamind: do not edit by hand -->"
SUPPORTED_VERSIONS = (1, 2)
CURRENT_VERSION = 2


class RegistryError(ValueError):
    """The registry is missing, unreadable, or violates the schema."""

    code = "registry_invalid"


class RegistryNotInitialized(RegistryError):
    """No registry exists at this root yet."""

    code = "not_initialized"


@dataclass
class Budgets:
    """Context and lifecycle budgets. All values are deliberately small by default."""

    max_candidates: int = 5
    max_context_chars: int = 8000
    stale_days: int = 180
    micro_wiki_pages: int = 4
    top_level_topics: int = 3


@dataclass
class ModelAccess:
    """What a local or cloud model context may receive. "" means: derive."""

    local: str = ""
    cloud: str = ""


@dataclass
class SourcePolicy:
    """Where sources may come from and how quoting is governed."""

    summary: str = ""
    allowlist: str = ""
    allowlist_status: str = "none"  # approved | proposed | none


@dataclass
class Freshness:
    """Declared freshness expectations. Staleness itself is computed, never stored."""

    half_life_days: int | None = None
    last_confirmed: str = ""


@dataclass
class ContextBudget:
    """Optional per-wiki overrides of the registry context budgets."""

    max_candidates: int | None = None
    max_context_chars: int | None = None


@dataclass
class WikiEntry:
    """One registered wiki. All paths are root-relative POSIX strings.

    The v1 fields (name, path, privacy, description, keywords, card, digest,
    index) are always present. The v2 card fields default to empty, which the
    access policy layer reads as "derive the most restrictive honest value".
    """

    name: str
    path: str
    privacy: str = "public-reference"
    description: str = ""
    keywords: list[str] = field(default_factory=list)
    card: str = ""
    digest: str = ""
    index: str = ""
    # --- schema v2 card fields -------------------------------------------------
    purpose: str = ""
    answers: list[str] = field(default_factory=list)
    does_not_answer: list[str] = field(default_factory=list)
    scope_boundaries: str = ""
    owners: list[str] = field(default_factory=list)
    sensitivity: str = ""
    model_access: ModelAccess = field(default_factory=ModelAccess)
    routing_mode: str = ""
    source_policy: SourcePolicy = field(default_factory=SourcePolicy)
    freshness: Freshness = field(default_factory=Freshness)
    examples: list[str] = field(default_factory=list)
    triggers: list[str] = field(default_factory=list)
    negative_triggers: list[str] = field(default_factory=list)
    dependencies: list[str] = field(default_factory=list)
    context_budget: ContextBudget = field(default_factory=ContextBudget)
    catalog_visibility: str = ""
    # Phase 3: provisional local wikis are not trusted until evaluated.
    provisional: bool = False


@dataclass
class Registry:
    version: int = 1
    budgets: Budgets = field(default_factory=Budgets)
    wikis: list[WikiEntry] = field(default_factory=list)

    def wiki_by_name(self, name: str) -> WikiEntry | None:
        for wiki in self.wikis:
            if wiki.name == name:
                return wiki
        return None


_BUDGET_FIELDS = (
    "max_candidates",
    "max_context_chars",
    "stale_days",
    "micro_wiki_pages",
    "top_level_topics",
)
_WIKI_FIELDS_V1 = ("name", "path", "privacy", "description", "keywords", "card", "digest", "index")
_WIKI_FIELDS_V2 = (
    *_WIKI_FIELDS_V1,
    "purpose",
    "answers",
    "does_not_answer",
    "scope_boundaries",
    "owners",
    "sensitivity",
    "model_access",
    "routing_mode",
    "source_policy",
    "freshness",
    "examples",
    "triggers",
    "negative_triggers",
    "dependencies",
    "context_budget",
    "catalog_visibility",
    "provisional",
)


def _type_name(value: object) -> str:
    return type(value).__name__


def _require_int(label: str, value: object) -> int:
    """Accept only genuine integers; JSON booleans are ints in Python but not budgets."""
    if isinstance(value, bool) or not isinstance(value, int):
        raise RegistryError(f"{label} must be an integer, got {_type_name(value)}")
    return value


def _require_str(label: str, value: object) -> str:
    if not isinstance(value, str):
        raise RegistryError(f"{label} must be a string, got {_type_name(value)}")
    return value


def _require_str_list(label: str, value: object) -> list[str]:
    if not isinstance(value, list):
        raise RegistryError(f"{label} must be a list of strings, got {_type_name(value)}")
    return [_require_str(f"{label}[{index}]", item) for index, item in enumerate(value)]


def _require_mapping(label: str, value: object) -> dict[str, object]:
    if not isinstance(value, dict):
        raise RegistryError(f"{label} must be a JSON object, got {_type_name(value)}")
    return {_require_str(f"{label} key", key): item for key, item in value.items()}


def _reject_unknown(label: str, data: dict[str, object], allowed: tuple[str, ...]) -> None:
    unknown = sorted(set(data) - set(allowed))
    if unknown:
        raise RegistryError(f"{label} has unknown field(s): {', '.join(unknown)}")


def _optional_int(label: str, value: object) -> int | None:
    if value is None:
        return None
    return _require_int(label, value)


def _budgets_from_json(value: object) -> Budgets:
    data = _require_mapping("budgets", value)
    _reject_unknown("budgets", data, _BUDGET_FIELDS)
    defaults = Budgets()
    values = {
        name: _require_int(f"budget {name}", data[name])
        if name in data
        else getattr(defaults, name)
        for name in _BUDGET_FIELDS
    }
    return Budgets(
        max_candidates=values["max_candidates"],
        max_context_chars=values["max_context_chars"],
        stale_days=values["stale_days"],
        micro_wiki_pages=values["micro_wiki_pages"],
        top_level_topics=values["top_level_topics"],
    )


def _model_access_from_json(label: str, value: object) -> ModelAccess:
    data = _require_mapping(label, value)
    _reject_unknown(label, data, ("local", "cloud"))
    access = ModelAccess(
        local=_require_str(f"{label} local", data.get("local", "")),
        cloud=_require_str(f"{label} cloud", data.get("cloud", "")),
    )
    for axis in ("local", "cloud"):
        level = getattr(access, axis)
        if level and level not in MODEL_ACCESS_LEVELS:
            raise RegistryError(
                f"{label} {axis} must be one of {', '.join(MODEL_ACCESS_LEVELS)}, got: {level}"
            )
    return access


def _source_policy_from_json(label: str, value: object) -> SourcePolicy:
    data = _require_mapping(label, value)
    _reject_unknown(label, data, ("summary", "allowlist", "allowlist_status"))
    policy = SourcePolicy(
        summary=_require_str(f"{label} summary", data.get("summary", "")),
        allowlist=_require_str(f"{label} allowlist", data.get("allowlist", "")),
        allowlist_status=_require_str(
            f"{label} allowlist_status", data.get("allowlist_status", "none")
        ),
    )
    if policy.allowlist_status not in ALLOWLIST_STATUSES:
        raise RegistryError(
            f"{label} allowlist_status must be one of {', '.join(ALLOWLIST_STATUSES)}, "
            f"got: {policy.allowlist_status}"
        )
    return policy


def _freshness_from_json(label: str, value: object) -> Freshness:
    data = _require_mapping(label, value)
    _reject_unknown(label, data, ("half_life_days", "last_confirmed"))
    freshness = Freshness(
        half_life_days=_optional_int(f"{label} half_life_days", data.get("half_life_days")),
        last_confirmed=_require_str(f"{label} last_confirmed", data.get("last_confirmed", "")),
    )
    if freshness.half_life_days is not None and freshness.half_life_days <= 0:
        raise RegistryError(f"{label} half_life_days must be positive")
    if freshness.last_confirmed:
        try:
            date.fromisoformat(freshness.last_confirmed)
        except ValueError:
            raise RegistryError(
                f"{label} last_confirmed must be an ISO date: {freshness.last_confirmed}"
            ) from None
    return freshness


def _context_budget_from_json(label: str, value: object) -> ContextBudget:
    data = _require_mapping(label, value)
    _reject_unknown(label, data, ("max_candidates", "max_context_chars"))
    budget = ContextBudget(
        max_candidates=_optional_int(f"{label} max_candidates", data.get("max_candidates")),
        max_context_chars=_optional_int(
            f"{label} max_context_chars", data.get("max_context_chars")
        ),
    )
    for name in ("max_candidates", "max_context_chars"):
        value_set = getattr(budget, name)
        if value_set is not None and value_set <= 0:
            raise RegistryError(f"{label} {name} must be positive")
    return budget


def _wiki_from_json(position: int, value: object, version: int) -> WikiEntry:
    label = f"wikis[{position}]"
    data = _require_mapping(label, value)
    allowed = _WIKI_FIELDS_V2 if version >= 2 else _WIKI_FIELDS_V1
    if version < 2:
        v2_fields = sorted((set(data) - set(allowed)) & set(_WIKI_FIELDS_V2))
        if v2_fields:
            raise RegistryError(
                f"{label} sets v2 field(s) {', '.join(v2_fields)} but the registry is "
                "version 1; run 'megamind-axi migrate' first"
            )
    _reject_unknown(label, data, allowed)
    defaults = WikiEntry(name="", path="")
    wiki = WikiEntry(
        name=_require_str(f"{label} name", data.get("name", defaults.name)),
        path=_require_str(f"{label} path", data.get("path", defaults.path)),
        privacy=_require_str(f"{label} privacy", data.get("privacy", defaults.privacy)),
        description=_require_str(f"{label} description", data.get("description", "")),
        keywords=_require_str_list(f"{label} keywords", data.get("keywords", [])),
        card=_require_str(f"{label} card", data.get("card", "")),
        digest=_require_str(f"{label} digest", data.get("digest", "")),
        index=_require_str(f"{label} index", data.get("index", "")),
    )
    if version < 2:
        return wiki
    wiki.purpose = _require_str(f"{label} purpose", data.get("purpose", ""))
    wiki.answers = _require_str_list(f"{label} answers", data.get("answers", []))
    wiki.does_not_answer = _require_str_list(
        f"{label} does_not_answer", data.get("does_not_answer", [])
    )
    wiki.scope_boundaries = _require_str(
        f"{label} scope_boundaries", data.get("scope_boundaries", "")
    )
    wiki.owners = _require_str_list(f"{label} owners", data.get("owners", []))
    wiki.sensitivity = _require_str(f"{label} sensitivity", data.get("sensitivity", ""))
    wiki.routing_mode = _require_str(f"{label} routing_mode", data.get("routing_mode", ""))
    wiki.examples = _require_str_list(f"{label} examples", data.get("examples", []))
    wiki.triggers = _require_str_list(f"{label} triggers", data.get("triggers", []))
    wiki.negative_triggers = _require_str_list(
        f"{label} negative_triggers", data.get("negative_triggers", [])
    )
    wiki.dependencies = _require_str_list(f"{label} dependencies", data.get("dependencies", []))
    wiki.catalog_visibility = _require_str(
        f"{label} catalog_visibility", data.get("catalog_visibility", "")
    )
    provisional = data.get("provisional", False)
    if not isinstance(provisional, bool):
        raise RegistryError(f"{label} provisional must be a boolean")
    wiki.provisional = provisional
    if "model_access" in data:
        wiki.model_access = _model_access_from_json(f"{label} model_access", data["model_access"])
    if "source_policy" in data:
        wiki.source_policy = _source_policy_from_json(
            f"{label} source_policy", data["source_policy"]
        )
    if "freshness" in data:
        wiki.freshness = _freshness_from_json(f"{label} freshness", data["freshness"])
    if "context_budget" in data:
        wiki.context_budget = _context_budget_from_json(
            f"{label} context_budget", data["context_budget"]
        )
    return wiki


def _require_relative(label: str, value: str) -> None:
    if value.startswith("/") or value.startswith("~") or ":" in value.split("/")[0]:
        raise RegistryError(f"{label} must be a root-relative path, got: {value}")
    if ".." in Path(value).parts:
        raise RegistryError(f"{label} must not contain '..': {value}")


def _default_v2_entry() -> WikiEntry:
    return WikiEntry(name="", path="")


def _check_v2_field_defaults(version: int, name: str, wiki: WikiEntry) -> None:
    """A v1 registry must not carry v2 card data; migrate first."""
    if version >= 2:
        return
    default = _default_v2_entry()
    for field_name in _WIKI_FIELDS_V2:
        if field_name in _WIKI_FIELDS_V1:
            continue
        if getattr(wiki, field_name) != getattr(default, field_name):
            raise RegistryError(
                f"wiki {name} sets v2 field '{field_name}' but the registry is version "
                f"{version}; run 'megamind-axi migrate' first"
            )


def _validate_wiki_entry(
    position: int, wiki: WikiEntry, version: int, seen: set[str], allow_unset_privacy: bool = False
) -> None:
    """Validate one entry. Every violation is a RegistryError, never a crash."""
    if not isinstance(wiki, WikiEntry):
        raise RegistryError(f"wikis[{position}] must be a wiki entry, got {_type_name(wiki)}")
    name = _require_str(f"wikis[{position}] name", wiki.name)
    if not name:
        raise RegistryError("wiki entry without a name")
    if name in seen:
        raise RegistryError(f"duplicate wiki name: {name}")
    seen.add(name)
    _check_v2_field_defaults(version, name, wiki)
    _require_str_list(f"wiki {name} keywords", wiki.keywords)
    if not _require_str(f"wiki {name} path", wiki.path):
        raise RegistryError(f"wiki {name} has no path")
    for label, value in (
        (f"wiki {name} path", wiki.path),
        (f"wiki {name} card", _require_str(f"wiki {name} card", wiki.card)),
        (f"wiki {name} digest", _require_str(f"wiki {name} digest", wiki.digest)),
        (f"wiki {name} index", _require_str(f"wiki {name} index", wiki.index)),
        (f"wiki {name} source_policy allowlist", wiki.source_policy.allowlist),
    ):
        if value:
            _require_relative(label, value)
    if not wiki.privacy and not allow_unset_privacy:
        raise RegistryError(f"wiki {wiki.name} has no privacy class")
    if wiki.privacy and wiki.privacy not in PRIVACY_CLASSES:
        raise RegistryError(
            f"wiki {wiki.name} has invalid privacy class: {wiki.privacy} "
            f"(expected one of {', '.join(PRIVACY_CLASSES)})"
        )
    if wiki.sensitivity and wiki.sensitivity not in SENSITIVITY_CLASSES:
        raise RegistryError(
            f"wiki {name} has invalid sensitivity: {wiki.sensitivity} "
            f"(expected one of {', '.join(SENSITIVITY_CLASSES)})"
        )
    if wiki.routing_mode and wiki.routing_mode not in ROUTING_MODES:
        raise RegistryError(
            f"wiki {name} has invalid routing_mode: {wiki.routing_mode} "
            f"(expected one of {', '.join(ROUTING_MODES)})"
        )
    if wiki.catalog_visibility and wiki.catalog_visibility not in CATALOG_VISIBILITIES:
        raise RegistryError(
            f"wiki {name} has invalid catalog_visibility: {wiki.catalog_visibility} "
            f"(expected one of {', '.join(CATALOG_VISIBILITIES)})"
        )
    if not isinstance(wiki.provisional, bool):
        raise RegistryError(f"wiki {name} provisional must be a boolean")


def validate_registry(registry: Registry) -> None:
    """Enforce the registry schema. Every violation is a RegistryError, never a crash."""
    _require_int("version", registry.version)
    if registry.version not in SUPPORTED_VERSIONS:
        raise RegistryError(f"unsupported registry version: {registry.version}")
    budgets = registry.budgets
    for name in _BUDGET_FIELDS:
        budget = _require_int(f"budget {name}", getattr(budgets, name))
        if name in ("max_candidates", "max_context_chars", "stale_days") and budget <= 0:
            raise RegistryError(f"budget {name} must be positive")
    if not isinstance(registry.wikis, list):
        raise RegistryError(f"wikis must be a list, got {_type_name(registry.wikis)}")
    seen: set[str] = set()
    for position, wiki in enumerate(registry.wikis):
        _validate_wiki_entry(position, wiki, registry.version, seen)


def registry_file(root: Path) -> Path:
    return resolve_contained(root, REGISTRY_PATH)


def load_registry(root: Path) -> Registry:
    path = registry_file(root)
    if not path.is_file():
        raise RegistryNotInitialized(
            f"no registry at {REGISTRY_PATH.as_posix()}; run 'megamind-axi init .' first"
        )
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise RegistryError(f"registry is not valid JSON: {error}") from error
    data = _require_mapping("registry root", raw)
    _reject_unknown("registry", data, ("version", "budgets", "wikis"))
    version = _require_int("version", data.get("version", 0))
    raw_wikis = data.get("wikis", [])
    if not isinstance(raw_wikis, list):
        raise RegistryError(f"wikis must be a list, got {_type_name(raw_wikis)}")
    registry = Registry(
        version=version,
        budgets=_budgets_from_json(data.get("budgets", {})),
        wikis=[
            _wiki_from_json(position, entry, version) for position, entry in enumerate(raw_wikis)
        ],
    )
    validate_registry(registry)
    return registry


def _wiki_to_data(wiki: WikiEntry, version: int) -> dict[str, object]:
    """Serialize one entry. v2 fields appear only when set, so files stay small."""
    data: dict[str, object] = {
        "name": wiki.name,
        "path": wiki.path,
        "privacy": wiki.privacy,
        "description": wiki.description,
        "keywords": wiki.keywords,
        "card": wiki.card,
        "digest": wiki.digest,
        "index": wiki.index,
    }
    if version < 2:
        return data
    default = _default_v2_entry()
    for field_name in _WIKI_FIELDS_V2:
        if field_name in _WIKI_FIELDS_V1:
            continue
        value = getattr(wiki, field_name)
        if value != getattr(default, field_name):
            data[field_name] = asdict(value) if hasattr(value, "__dataclass_fields__") else value
    return data


def registry_to_data(registry: Registry) -> dict[str, object]:
    return {
        "version": registry.version,
        "budgets": asdict(registry.budgets),
        "wikis": [_wiki_to_data(wiki, registry.version) for wiki in registry.wikis],
    }


def serialize_registry(registry: Registry) -> str:
    """The canonical on-disk form: sorted keys, two-space indent, trailing newline."""
    validate_registry(registry)
    return json.dumps(registry_to_data(registry), indent=2, sort_keys=True) + "\n"


def save_registry(root: Path, registry: Registry) -> Path:
    return atomic_write(root, REGISTRY_PATH, serialize_registry(registry))


def migrate_registry(root: Path) -> tuple[Registry, bool, list[str]]:
    """Upgrade a v1 registry to v2 in place. Returns (registry, changed, notes).

    The derived access posture is written out explicitly so the migrated file
    is self-describing, except for company-private wikis: their cloud access
    stays unset (derived: none) until an owner sets an explicit policy, which
    is exactly what doctor keeps reminding about. Idempotent: a v2 registry is
    returned unchanged with ``changed`` false.
    """
    registry = load_registry(root)
    if registry.version >= CURRENT_VERSION:
        return registry, False, []
    notes: list[str] = []
    for wiki in registry.wikis:
        wiki.sensitivity = PRIVACY_SENSITIVITY.get(wiki.privacy, "")
        if wiki.privacy == "company-private":
            notes.append(
                f"{wiki.name}: cloud access left unset (defaults to none); "
                "set an explicit model_access policy"
            )
            continue
        derived = {
            "public-reference": ModelAccess(local="full", cloud="full"),
            "personal-local": ModelAccess(local="full", cloud="digest-only"),
            "digest-only": ModelAccess(local="digest-only", cloud="digest-only"),
            "pointer-only": ModelAccess(local="none", cloud="none"),
        }[wiki.privacy]
        wiki.model_access = derived
        if wiki.privacy == "pointer-only":
            wiki.routing_mode = "pointer"
    registry.version = CURRENT_VERSION
    backup = backup_existing(root, REGISTRY_PATH)
    save_registry(root, registry)
    append_audit(
        root,
        "migrate",
        {
            "path": REGISTRY_PATH.as_posix(),
            "from_version": 1,
            "to_version": CURRENT_VERSION,
            "backup": backup.name if backup else None,
        },
    )
    return registry, True, notes


def generate_router(registry: Registry) -> str:
    """Render the generated top-level router page from the registry.

    The router is a human/agent readable projection of the registry. It is
    regenerated, never hand-edited; doctor verifies it matches the registry.
    """
    lines = [
        ROUTER_HEADER,
        "# Router",
        "",
        "Start here. Open the smallest artifact that can answer the question:",
        "routing card, then digest, then index, then exact pages.",
        "",
    ]
    for wiki in sorted(registry.wikis, key=lambda w: w.name):
        lines.append(f"## {wiki.name}")
        lines.append("")
        if wiki.description:
            lines.append(wiki.description)
            lines.append("")
        lines.append(f"- path: `{wiki.path}`")
        lines.append(f"- privacy: `{wiki.privacy}`")
        if wiki.card:
            lines.append(f"- card: `{wiki.card}`")
        if wiki.digest:
            lines.append(f"- digest: `{wiki.digest}`")
        if wiki.index:
            lines.append(f"- index: `{wiki.index}`")
        if wiki.keywords:
            lines.append(f"- keywords: {', '.join(wiki.keywords)}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"
